# Generated by Django 2.2.7 on 2019-11-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='depart',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
