# Generated by Django 2.2.1 on 2019-11-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='license_on',
            field=models.CharField(default='유통관리사', max_length=200, null=True),
        ),
    ]
