# Generated by Django 2.2.7 on 2019-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191114_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
