# Generated by Django 2.2.7 on 2019-11-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191114_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Student'),
        ),
    ]
