# Generated by Django 2.2.7 on 2019-11-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191114_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
    ]
