# Generated by Django 2.2.7 on 2019-11-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default=1, max_length=200, null=True),
        ),
    ]
