# Generated by Django 2.1.1 on 2019-11-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_student_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='title',
        ),
    ]
